dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
script:
  - npm i truffle ganache-core 
  - ganache-cli -i 1002 -l 8000000 > /dev/null & 
  - truffle test 