dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
script:
  - npm i ganache-cli
  - ganache-cli -i 1002 -l 8000000 > /dev/null &
  - npm run truffle:test
  - npm run truffle:migrate -- --netwotk=development
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: "dist"
  on:
    branch: "master"